### ISSUE TITLE
Code doesn't compile. Method "BestSizeEstimator" is missing

### ISSUE THREAD

**Issue by azahran007** [DevExpress-Examples/Reporting_how-to-dynamically-generate-a-report-and-bind-it-to-a-collection-of-objects-e652#1]
Cloned the repository and the C# code seems to be incomplete

**Comment by vasyaste** [comment]
Hi @azahran007,

I do not see the BestSizeEstimator method calls in the code that is used in this code example. So, maybe you posted this issue to a wrong repository?
In any case, feel free to share a link to the repository's code file where you found the BestSizeEstimator code call if I missed it.
